import './styles/style.scss';
import './img/vk.png';
import './img/instagram.png';
import './img/twt.svg';
import './img/post-it.png';
import './img/post-it.svg';
import './img/VK.com-logo.svg';
import './img/Instagram-Logo.wine.svg';
import './carusel.js'
