name: HTML Check

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2.3.2

      - name: Install Packages
        run: |
          npm install

      - name: Build
        run: |
          npm run build

      - name: Checks HTML5
        uses: Cyb3r-Jak3/html5validator-action-experimental@v1
        with:
          root: ./dist
